version: '3.6'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - application

  application:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4"
    volumes:
      - .:/code
    expose:
      - "8000"